// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCSHIZvuqmA5pMTJ4uKbBVeBPWulFUzog',
    appId: '1:409824466911:web:1e4e8baf55a3acad47566a',
    messagingSenderId: '409824466911',
    projectId: 'e-commerce-1-d62b9',
    authDomain: 'e-commerce-1-d62b9.firebaseapp.com',
    storageBucket: 'e-commerce-1-d62b9.firebasestorage.app',
    measurementId: 'G-JHHXLPX138',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF4ePfAlBcUenEREpk_x3A8YAE0zd10Hc',
    appId: '1:409824466911:android:816ddcfb81140a6547566a',
    messagingSenderId: '409824466911',
    projectId: 'e-commerce-1-d62b9',
    storageBucket: 'e-commerce-1-d62b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU2AQROk5JX4LbOzX8M_OExpW0GT2ZL5E',
    appId: '1:409824466911:ios:0c02ae8c798f11e247566a',
    messagingSenderId: '409824466911',
    projectId: 'e-commerce-1-d62b9',
    storageBucket: 'e-commerce-1-d62b9.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU2AQROk5JX4LbOzX8M_OExpW0GT2ZL5E',
    appId: '1:409824466911:ios:0c02ae8c798f11e247566a',
    messagingSenderId: '409824466911',
    projectId: 'e-commerce-1-d62b9',
    storageBucket: 'e-commerce-1-d62b9.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCSHIZvuqmA5pMTJ4uKbBVeBPWulFUzog',
    appId: '1:409824466911:web:27df8a9b144fa4b247566a',
    messagingSenderId: '409824466911',
    projectId: 'e-commerce-1-d62b9',
    authDomain: 'e-commerce-1-d62b9.firebaseapp.com',
    storageBucket: 'e-commerce-1-d62b9.firebasestorage.app',
    measurementId: 'G-00QZDXYZVW',
  );
}
